### ISSUE TITLE
Support for m.youtube.com

### ISSUE THREAD

**Issue by chirag127** [mchangrh/sb.js#1]

**Comment by mchangrh** [comment]
Mobile YouTube doesn't have polymer events so it might only be possible to add it as a scriptlet.

**Comment by chirag127** [comment]
> Mobile YouTube doesn't have polymer events so it might only be possible to add it as a scriptlet.

I have no idea what is a scriptlet or how to use it.

**Comment by mchangrh** [comment]
This doesn't work since mobile youtube has a fake video element and adding a check for it is too taxing

**Comment by Julmik647** [comment]
Even if mobile version would be helpful especially for ios users, it's unfortunitly not that easy to do.

**Comment by DimitrisKalaboukas** [comment]
@mchangrh It would be very useful if it became technically possible to implement an SB.js version for `m.youtube.com` to be used e.g. in extensions of AdGuard app for Android or in browsers that allow user scripts, as many popular mobile browsers like Google Chrome, Brave, Opera, Vivaldi etc. don’t support extensions.
