### ISSUE TITLE
`sb-config-user.js` does not load in environments that do not support top-level await statements

### ISSUE THREAD

**Issue by chaorace** [mchangrh/sb.js#10]
**Expected Behavior**
The userscript version that has a configuration UI (`sb-config-user.js`) should be compatible with the same set of environments that the other versions are.

**Actual Behavior**
Userscript environments that don't support top-level await (e.g.: ViolentMonkey, Qutebrowser) will crash out of the `sb-config-user.js` userscript with the following error:
> await is only valid in async function

![1684691242](https://github.com/mchangrh/sb.js/assets/6462592/8138981b-f61e-4490-a6f7-4ed0c2e6d8a1)

**Additional Notes**
[Top-level await is not a standard feature in userscript environments](https://github.com/violentmonkey/violentmonkey/issues/833#issuecomment-748643830) and implementations that do provide it are arguably going against the ECMA spec. I feel that it would be good for compatibility to do away with any dependencies on this behavior.

**Comment by chaorace** [comment]
Upon closer examination, there's actually no point in using the few top-level `await` statements that currently exist, since the `GM_getValue`/`GM_setValue` API methods that this script uses don't actually return Promises (unlike the newer `GM.getValue`/`GM.setValue` API methods).

In light of this fact, I'm fairly confident that it should be possible to fix this issue by simply deleting all usages of the `await`/`async` keywords from [/src/gm_config.js](https://github.com/mchangrh/sb.js/blob/d94fb7dd48b449d9a50437a292337a65b92e5bf9/src/gm_config.js) with no additional changes necessary.

**Comment by mchangrh** [comment]
My understanding was that GM_set/getValue returned promises but since I am targeting tampermonkey, promiseless is fine
