### ISSUE TITLE
Invidious support?

### ISSUE THREAD

**Issue by ghost** [mchangrh/sb.js#3]
I use yewtu.be as an Invidious instance and would like to use this UserScript instead of a browser extension.

What changes would I need to make to the script (and which file would I install into my US manager)?

**Comment by mchangrh** [comment]
hilariously enough, the invidious format closely matches youtube, so (almost) no code changes are necessary.

full-video labels will not show up, that is one breaking change

it should be as easy as going into your userscript manager and adding yewtu.be into the User Includes/Excludes list. Probably something along the lines of

`https://yewtu.be/*`

![image](https://user-images.githubusercontent.com/15132783/194669533-96ad265e-9c5d-4dd9-8c1a-82bc27d5fb5a.png)

I would still recommend the browser extension ;)
